require("dc.core")
require("dc.packer")

require("dc.plugins.autopairs")
require("dc.plugins.comment")
require("dc.plugins.cmp")
require("dc.plugins.gitsigns")
require("dc.plugins.lsp")
require("dc.plugins.lualine")
require("dc.plugins.nightfox")
require("dc.plugins.telescope")
require("dc.plugins.tree")
require("dc.plugins.treesitter")
